"""
edit_history.py — Comprehensive edit history tracking.

Stores every edit with metadata for:
  - Audit trail (who, what, when, why)
  - Undo/redo functionality
  - Impact analysis
  - Learning from past edits

Designed to be serialized for persistence.
"""

from __future__ import annotations

import json
import uuid
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import List, Dict, Optional, Any

from core.logger import setup_logger


logger = setup_logger(__name__)


@dataclass
class EditEntry:
    """
    One edit entry in the history.

    Attributes:
        edit_id:         Unique identifier for this edit.
        timestamp:       When the edit occurred.
        request_id:      ID of the request that triggered the edit.
        user_prompt:     Original user prompt.
        model_name:      Name of the AI model that generated the edit.
        files:           List of affected file paths.
        rollback_id:     ID of the rollback checkpoint created before this edit.
        changes_summary: Brief summary of changes.
        metadata:        Extra data (confidence, tokens, etc.).
    """
    edit_id:        str
    timestamp:      datetime
    request_id:     str
    user_prompt:    str
    model_name:     Optional[str]
    files:          List[str]
    rollback_id:    str
    changes_summary: str
    metadata:       Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for serialization."""
        return {
            "edit_id": self.edit_id,
            "timestamp": self.timestamp.isoformat(),
            "request_id": self.request_id,
            "user_prompt": self.user_prompt,
            "model_name": self.model_name,
            "files": self.files,
            "rollback_id": self.rollback_id,
            "changes_summary": self.changes_summary,
            "metadata": self.metadata,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> EditEntry:
        """Create from dictionary."""
        return cls(
            edit_id=data["edit_id"],
            timestamp=datetime.fromisoformat(data["timestamp"]),
            request_id=data["request_id"],
            user_prompt=data["user_prompt"],
            model_name=data.get("model_name"),
            files=data.get("files", []),
            rollback_id=data["rollback_id"],
            changes_summary=data.get("changes_summary", ""),
            metadata=data.get("metadata", {}),
        )


class EditHistory:
    """
    Manages edit history with support for:
      - Long-term persistence
      - Undo/redo
      - Query by criteria
      - Impact analysis

    Usage:
        history = EditHistory(project_root)
        history.add_entry(edit_entry)
        entries = history.get_by_file(file_path)
        history.undo(last_n=1)
    """

    def __init__(self, project_root: str, max_entries: int = 1000) -> None:
        self._root = Path(project_root)
        self._history_file = self._root / ".ai_history" / "edits.json"
        self._history_file.parent.mkdir(exist_ok=True)

        self._entries: List[EditEntry] = []
        self._max_entries = max_entries

        self._load_history()
        logger.debug(f"EditHistory initialized (max_entries={max_entries}).")

    # ── Public API ─────────────────────────────────────────────────────────

    def add_entry(self, entry: EditEntry) -> None:
        """
        Add a new edit entry to history.

        Args:
            entry: The EditEntry to store.
        """
        self._entries.insert(0, entry)
        self._trim_entries()
        self._save_history()
        logger.info(
            f"EditHistory: added entry {entry.edit_id[:8]} for "
            f"{len(entry.files)} file(s)."
        )

    def get_all(self) -> List[EditEntry]:
        """Return all edit entries, newest first."""
        return list(self._entries)

    def get_by_request_id(self, request_id: str) -> List[EditEntry]:
        """Return entries matching a specific request ID."""
        return [e for e in self._entries if e.request_id == request_id]

    def get_by_file(self, file_path: str) -> List[EditEntry]:
        """Return entries that affected a specific file."""
        file_path = str(Path(file_path))
        return [e for e in self._entries if file_path in e.files]

    def get_by_model(self, model_name: str) -> List[EditEntry]:
        """Return entries generated by a specific model."""
        return [e for e in self._entries if e.model_name == model_name]

    def get_by_time_range(
        self,
        start: Optional[datetime] = None,
        end: Optional[datetime] = None,
    ) -> List[EditEntry]:
        """Return entries within a time range."""
        result = []
        for e in self._entries:
            if start and e.timestamp < start:
                continue
            if end and e.timestamp > end:
                continue
            result.append(e)
        return result

    def undo(self, last_n: int = 1) -> List[EditEntry]:
        """
        Undo the last N edits by rolling back to their checkpoints.

        Args:
            last_n: Number of recent edits to undo.

        Returns:
            List of entries that were undone.
        """
        undone = []
        for entry in self._entries[:last_n]:
            if entry.rollback_id:
                logger.info(
                    f"EditHistory: undoing edit {entry.edit_id[:8]}, "
                    f"rollback_id={entry.rollback_id[:8]}"
                )
                undone.append(entry)

        return undone

    def search(self, query: str, case_sensitive: bool = False) -> List[EditEntry]:
        """
        Search entries by prompt or file content.

        Args:
            query: Text to search for.
            case_sensitive: Whether to match case exactly.

        Returns:
            Matching entries.
        """
        if not case_sensitive:
            query = query.lower()

        results = []
        for e in self._entries:
            text = e.user_prompt if case_sensitive else e.user_prompt.lower()
            if query in text:
                results.append(e)
        return results

    def stats(self) -> Dict[str, Any]:
        """Return history statistics."""
        if not self._entries:
            return {
                "total_edits": 0,
                "files_edited": 0,
                "models_used": 0,
            }

        files = set()
        models = set()
        for e in self._entries:
            files.update(e.files)
            if e.model_name:
                models.add(e.model_name)

        return {
            "total_edits": len(self._entries),
            "files_edited": len(files),
            "models_used": len(models),
            "oldest": self._entries[-1].timestamp.isoformat() if self._entries else None,
            "newest": self._entries[0].timestamp.isoformat() if self._entries else None,
        }

    # ── Persistence ───────────────���──────────────────────────────────────────

    def _load_history(self) -> None:
        """Load history from disk."""
        if not self._history_file.exists():
            return

        try:
            data = json.loads(self._history_file.read_text(encoding="utf-8"))
            self._entries = [EditEntry.from_dict(d) for d in data]
        except (json.JSONDecodeError, KeyError) as exc:
            logger.error(f"EditHistory: failed to load history: {exc}")
            self._entries = []

    def _save_history(self) -> None:
        """Save history to disk."""
        data = [e.to_dict() for e in self._entries]
        self._history_file.write_text(
            json.dumps(data, indent=2),
            encoding="utf-8"
        )

    def _trim_entries(self) -> None:
        """Remove old entries if over the limit."""
        if len(self._entries) > self._max_entries:
            removed = self._entries[self._max_entries:]
            self._entries = self._entries[:self._max_entries]
            logger.info(
                f"EditHistory: trimmed {len(removed)} old entries "
                f"(max={self._max_entries})."
            )


def load_edit_history(project_root: str, max_entries: int = 1000) -> EditHistory:
    """Convenience function to load edit history."""
    return EditHistory(project_root, max_entries)


def create_edit_entry(
    request_id: str,
    user_prompt: str,
    model_name: Optional[str],
    files: List[str],
    rollback_id: str,
    changes_summary: str = "",
    metadata: Optional[Dict[str, Any]] = None,
) -> EditEntry:
    """Convenience function to create an edit entry."""
    return EditEntry(
        edit_id=f"edit_{uuid.uuid4().hex[:12]}",
        timestamp=datetime.now(),
        request_id=request_id,
        user_prompt=user_prompt,
        model_name=model_name,
        files=files,
        rollback_id=rollback_id,
        changes_summary=changes_summary,
        metadata=metadata or {},
    )